---
- name: Ensure EPEL repo is enabled
  ansible.builtin.dnf:
    name: epel-release
    state: latest

- name: Extra repo name
  ansible.builtin.set_fact:
    extra_repo: "{{ 'crb' if ansible_distribution_major_version | int > 8 else 'powertools' }}"

- name: "Check if extra repository is enabled {{ extra_repo }}"
  ansible.builtin.command:
    cmd: "dnf repolist {{ extra_repo }} --enabled"
  register: repolist
  changed_when: false

- name: "Enable repository {{ extra_repo }} "
  ansible.builtin.command:
    cmd: "dnf config-manager --enable {{ extra_repo }}"
  register: cmd_output
  changed_when: cmd_output.rc != 0
  when: extra_repo not in repolist.stdout

- name: Import EWC Packages GPG Key
  ansible.builtin.rpm_key:
    state: present
    key: https://nexus.ecmwf.int/repository/private-raw-repos-config/rocky/keys/ewc-rocky-gpg-key

- name: Add ECMWF repository
  ansible.builtin.yum_repository:
    name: ecmwf
    description: ECMWF Repository
    baseurl: "{{ repo_base }}/repository/private-rocky-{{ repo_suffix }}/{{ ansible_distribution_major_version }}/{{ ansible_distribution_version.split('.')[1] }}/rpms"
    gpgcheck: true
    enabled: true

- name: Check if MARS servers can be reached (ECMWF only)
  ansible.builtin.getent:
    database: hosts
    key: marsod.ecmwf.int
  register: marsod_lookup
  ignore_errors: true

- name: Trust the traffic coming from the ECMWF LAN in the local firewall
  ansible.posix.firewalld:
    zone: trusted
    source: 10.0.0.0/8
    state: enabled
    permanent: true
    immediate: true
  when: marsod_lookup.ansible_facts.getent_hosts is defined

- name: "Install MARS client"
  ansible.builtin.dnf:
    name: mars-client-cloud
    state: latest
